---
title: "p8105_hw6_ep3045"
author: "Ellen Park"
date: "2022-12-02"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	fig.height = 6,
	out.width = "90%",
	dpi = 200
)
```


```{r}
library(tidyverse)
library(labelled)
library(modelr)
```


```{r}
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "yeti",
  ggplot2.continuous.fill = "yeti"
)
```


## Problem 1

Import the data.

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


```{r}
weather_df %>% 
  bootstrap(n = 1000) %>% 
  mutate(
    models = map(strap, ~lm(tmax ~ tmin, data = .x) ),
    results = map(models, broom::glance)) %>% 
  select(-strap, -models) %>% 
  unnest(results) %>% 
  ggplot(aes(x = r.squared)) + 
  geom_density()
```

The $\hat{r}^2$ value is high, between 0.91 and 0.92. The bounds [0.89, 1] may be an explanation for the skewed distribution. For a confidence interval, we can take the 2.5% and 97.5% quantiles of the sample estimates. However, because the distribution is skewed, this would not produce the most accurate result. 


